In [1]:
import numpy as np

In [2]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
array = np.array(list)

In [6]:
type(array)

numpy.ndarray

In [8]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array(matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Indexing

In [9]:
array[0]

1

In [10]:
array[0] + array[7]

9

In [11]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
matrix[0, 2]

3

In [14]:
array[0:3] # slicing

array([1, 2, 3])

In [15]:
array[1:6]

array([2, 3, 4, 5, 6])

In [16]:
array[:6]

array([1, 2, 3, 4, 5, 6])

In [17]:
array[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
array[::3]

array([1, 4, 7])

In [20]:
array[-3:]

array([7, 8, 9])

In [21]:
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])