In [1]:
import numpy as np

In [2]:
array = np.arange(0, 11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array_slice = array[0:6]
array_slice

array([0, 1, 2, 3, 4, 5])

In [5]:
array_slice[:] = 0
array_slice

array([0, 0, 0, 0, 0, 0])

In [6]:
array

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [7]:
array_copy = array.copy()
array_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [8]:
array_copy[:] = 100
array_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [9]:
array

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])