In [1]:
import numpy as np

In [2]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand()

0.9808724795693701

In [16]:
np.random.rand(4)

array([0.601704  , 0.29156969, 0.89286536, 0.29258945])

In [18]:
np.random.rand(4, 4)

array([[0.6047978 , 0.36930938, 0.98976661, 0.06447426],
       [0.40859158, 0.44798937, 0.61188009, 0.26738871],
       [0.70031271, 0.33430516, 0.06984499, 0.82707248],
       [0.06241204, 0.20654003, 0.62193902, 0.42387029]])

In [19]:
np.random.randint(1, 15)

3

In [20]:
np.random.randint(1, 100, (10, 10))

array([[92, 39, 30, 64, 93, 47, 98, 32, 13,  8],
       [28, 51,  1, 53, 52, 51, 15, 44, 22, 74],
       [69, 35, 51, 61,  6, 94, 19, 33, 68, 57],
       [17, 28, 80, 91, 82,  7, 69, 96, 13, 58],
       [ 6, 68,  2, 65, 11, 92, 79, 60, 30, 62],
       [18, 69, 25, 97, 86, 93, 78, 86, 56, 81],
       [80, 70, 81, 34, 36, 25, 71, 34,  9, 90],
       [99,  6,  3,  7, 74, 17, 75, 13, 13, 26],
       [50, 90, 25, 40, 66, 24, 44, 91, 67, 80],
       [80, 89, 50, 94, 70,  3, 15, 23, 77, 67]])