In [1]:
import numpy as np

In [2]:
list = [1, 2]
list

[1, 2]

In [3]:
list * 2

[1, 2, 1, 2]

In [4]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array_two = array.copy()

## Operations

In [6]:
array * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
array + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
1 / array

/tmp/ipykernel_4264/1508088032.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / array


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
array ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
array + array_two

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
array * array_two

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
matrix = array.reshape(2, 5)
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
matrix_two = matrix.copy()

In [18]:
matrix * matrix_two

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [20]:
np.matmul(matrix, matrix_two.T)

array([[ 30,  80],
       [ 80, 255]])

In [21]:
matrix @ matrix_two.T

array([[ 30,  80],
       [ 80, 255]])