In [1]:
import numpy as np

In [2]:
array = np.linspace(1, 10, 10, dtype='int8')
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [5]:
condition_index = array > 5
condition_index

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
array[condition_index]
array[(array > 5) & (array < 9)]

array([6, 7, 8], dtype=int8)

In [9]:
array[array > 5] = 99
array

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [10]:
array[array == 99]

array([99, 99, 99, 99, 99], dtype=int8)