In [1]:
import numpy as np

In [7]:
array = np.array([1, 2, 3, 4])

In [3]:
array

array([1, 2, 3, 4])

In [4]:
array.dtype

dtype('int64')

In [5]:
array = np.array([1, 2, 3, 4], dtype='float64')
array.dtype

dtype('float64')

In [6]:
array

array([1., 2., 3., 4.])

In [8]:
array = np.array([0, 1, 2, 3, 4])
array = array.astype(np.bool_)
array

array([False,  True,  True,  True,  True])

In [9]:
array = array.astype(np.string_)
array

array([b'False', b'True', b'True', b'True', b'True'], dtype='|S5')