In [2]:
import numpy as np

In [3]:
array = np.random.randint(1, 20, 10)

In [4]:
matrix = array.reshape(2, 5)
matrix

array([[18,  8,  9,  3, 18],
       [17, 16,  2,  4, 16]])

In [5]:
array.max()

18

In [6]:
matrix.max(1)

array([18, 17])

In [7]:
array.argmax()

0

In [8]:
matrix.argmax(0)

array([0, 1, 0, 1, 0])

In [9]:
array.min()

2

In [10]:
matrix.min(0)

array([17,  8,  2,  3, 16])

In [11]:
array.argmin()

7

In [12]:
matrix.argmin(0)

array([1, 0, 1, 0, 1])

In [13]:
array.ptp()

16

In [15]:
matrix.ptp(0)

array([1, 8, 7, 1, 2])

In [17]:
np.percentile(array, 50)

12.5

In [18]:
array.sort()
array

array([ 2,  3,  4,  8,  9, 16, 16, 17, 18, 18])

In [19]:
np.median(array)

12.5

In [20]:
np.median(matrix, 0)

array([ 9. ,  9.5, 10.5, 13. , 13.5])

In [21]:
np.std(array)

6.252199612936235

In [22]:
np.var(array)

39.09

In [23]:
np.mean(array)

11.1

In [24]:
a = np.array([[1, 2], [ 3, 4]])
a

array([[1, 2],
       [3, 4]])

In [28]:
b = np.array([5, 6])
b = np.expand_dims(b, axis=0)

np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])