In [1]:
import numpy as np

In [2]:
array = np.random.randint(1, 10, (3, 2))

In [3]:
array.shape

(3, 2)

In [4]:
array

array([[4, 6],
       [3, 3],
       [3, 7]])

In [5]:
array.reshape(1, 6)

array([[4, 6, 3, 3, 3, 7]])

In [6]:
array.reshape(2, 3)

array([[4, 6, 3],
       [3, 3, 7]])

In [7]:
np.reshape(array, (1, 6))

array([[4, 6, 3, 3, 3, 7]])

In [8]:
np.reshape(array, (2, 3), 'C')

array([[4, 6, 3],
       [3, 3, 7]])

In [9]:
np.reshape(array, (2, 3), 'F')

array([[4, 3, 3],
       [3, 6, 7]])

In [10]:
np.reshape(array, (2, 3), 'A')

array([[4, 6, 3],
       [3, 3, 7]])